AWSTemplateFormatVersion: 2010-09-09
Description: >-
  API to ECS scale containers.

Transform:
- AWS::Serverless-2016-10-31

Resources:
  scaleContainer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/scale-container.addContainer
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get one item by id from a DynamoDB table.
      Environment:
        Variables:
          CLUSTER_NAME: cluster
          SERVICE_NAME: service
          DESIRED_COUNT: 10
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
